database:
  name: rma-local
  host: localhost
  port: 5432
  user: postgres
  password: postgres

spring:
  jpa:
    hibernate.show-sql: true

#UNCOMMENT FOR DEBUGGING
#logging:
#  level:
#    org.springframework: DEBUG